version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - yarn config set -H enableImmutableInstalls false
      - yarn install
  build:
    on-failure: ABORT
    commands:
      - yarn build
  post_build:
    on-failure: ABORT
    commands:
      - cp -R .ebextensions/ dist/.ebextensions
      - cp -R package.json dist/package.json
      - cp -R buildspec.yml dist/buildspec.yml
      - cp -R Procfile dist/Procfile
      - cp -R .pnp.cjs dist/.pnp.cjs
      - cp -R .pnp.loader.mjs dist/.pnp.loader.mjs
      - cp -R yarn.lock dist/yarn.lock
      - cp -R .yarnrc.yml dist/.yarnrc.yml
      - cp -R .yarn dist/.yarn
cache:
  paths:
    - '.yarn/**/*'
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'dist'
